services:
  - type: web
    name: pos-offline-docker
    env: docker
    plan: free
    branch: main
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://offline-wallet-pos-201-3.onrender.com
