android.useAndroidX=true
android.enableJetifier=true
# org.gradle.java.home=E:/DOWNLOADS/POS OFFLINE SFTWR/java-1.8.0-openjdk-1.8.0.492.b09-1.win.jdk.x86_64/java-1.8.0-openjdk-1.8.0.492.b09-1.win.jdk.x86_64
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false

# Signing Configurations
signing.storeFile=pos-release-key.keystore
signing.storePassword=pos123456
signing.keyAlias=pos_key
signing.keyPassword=pos123456
