const { open } = require('sqlite');
const sqlite3 = require('sqlite3');
const path = require('path');
(async () => {
  const db = await open({ filename: path.join(process.cwd(), 'data', 'database.sqlite'), driver: sqlite3.Database });
  const MID = 'MRC-1001';
  console.log('=== FINAL STATE AFTER ATOMIC CONVERSION ===');
  const a = await db.all('SELECT currency, balance FROM merchant_wallets WHERE merchant_id = ? ORDER BY currency', [MID]);
  console.log('Merchant wallets:', JSON.stringify(a, null, 2));
  const b = await db.all('SELECT asset, amount, is_mock, substr(meta,1,220) meta_head FROM merchant_crypto_balances WHERE merchant_id = ? ORDER BY asset', [MID]);
  console.log('Crypto balances:', JSON.stringify(b, null, 2));
  const c = await db.all("SELECT substr(id,1,18) id, type, amount, substr(currency,1,6) cur, status, substr(description,1,160) descr FROM ledger_entries ORDER BY id DESC LIMIT 10");
  console.log('Last 10 ledgers:');
  c.forEach(r => console.log(' ', r.id, r.type, String(r.amount).padStart(10), r.cur, ' ', r.status.padEnd(9), r.descr));
  const d = await db.get("SELECT id, from_currency, to_asset, from_amount, to_amount, backed_by_settlement_batch batch, status FROM merchant_internal_settlements WHERE id='int_conv_setl_offline_msslg0j9'");
  if (d) console.log('Internal settle:', JSON.stringify(d, null, 2));
  const e = await db.all("SELECT substr(mwt.id,1,16) id, type, amount, currency, source, substr(reference,1,60) reference FROM merchant_wallet_transactions mwt JOIN merchant_wallets mw ON mw.id = mwt.wallet_id WHERE mw.merchant_id = ? ORDER BY mwt.id DESC LIMIT 6", [MID]);
  console.log('Merchant wallet txns:', JSON.stringify(e, null, 2));
  const pos = await db.get("SELECT id, stan, amount_minor, currency, status, pan_masked, entry_mode, auth_mode, auth_code, merchant_id, terminal_id, batch_id FROM pos2013_transactions ORDER BY id DESC LIMIT 1");
  console.log('POS2013 row last:', JSON.stringify(pos, null, 2));
  const settle = await db.get("SELECT id, merchant_id, amount, currency, status, settled_at, substr(meta,1,160) meta_head FROM merchant_pos_settlements ORDER BY id DESC LIMIT 1");
  console.log('Settle row last:', JSON.stringify(settle, null, 2));
})();
