const mod = require('../node_modules/tronweb/lib/commonjs/index.js');
const TronWeb = mod.TronWeb || mod.default || mod;
const t = new TronWeb({ fullNode:'https://api.trongrid.io', solidityNode:'https://api.trongrid.io', eventServer:'https://api.trongrid.io' });
const a = t.utils.accounts.generateAccount();
console.log('');
console.log('=== NEW TRON HOT WALLET ===');
console.log('Address   :', a.address.base58);
console.log('PrivateKey:', a.privateKey);
console.log('');
console.log('Add to backend/.env:');
console.log('TRON_PRIVATE_KEY=' + a.privateKey);
console.log('TRON_WALLET_ADDRESS=' + a.address.base58);
console.log('');
console.log('Fund with: https://tronscan.org/#/address/' + a.address.base58);
console.log('Need: 200+ TRX (gas) + USDT TRC-20 (for withdrawals)');
